=== kepingwang/cell-society/data/cell-society.dtd
<!ELEMENT config (name,id,color,width,height,rows,cols,layout)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT color (val+)>
<!ELEMENT val (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT cols (#PCDATA)>
<!ELEMENT layout (row+)>
<!ELEMENT row (col+)>
<!ELEMENT col (#PCDATA)>

=== kepingwang/cell-society/data/fire1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE config SYSTEM "cell-society.dtd">
<config>
	<name>fire</name>
	<id>keping001</id>
	<color>
		<val>#F0F8FF</val>
		<val>#000000</val>
	</color>
	<width>300</width>
	<height>300</height>
	<rows>50</rows>
	<cols>50</cols>
	<probs>
		<val>0.1</val>
		<val>0.7</val>
		<val>0.2</val>
	</probs>
	<params>
		<val>0.4</val>
	</params>
</config>

=== kepingwang/cell-society/data/game_of_life2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE config SYSTEM "cell-society.dtd">
<config>
	<name>game_of_life</name>
	<id>keping001</id>
	<width>100</width>
	<height>100</height>
	<rows>5</rows>
	<cols>5</cols>
	<layout>
		<row>
			<col>1</col>
			<col>0</col>
			<col>1</col>
			<col>0</col>
			<col>1</col>
		</row>
		<row>
			<col>1</col>
			<col>1</col>
			<col>1</col>
			<col>0</col>
			<col>1</col>
		</row>
		<row>
			<col>1</col>
			<col>0</col>
			<col>0</col>
			<col>0</col>
			<col>1</col>
		</row>
		<row>
			<col>1</col>
			<col>1</col>
			<col>1</col>
			<col>0</col>
			<col>1</col>
		</row>
		<row>
			<col>1</col>
			<col>0</col>
			<col>0</col>
			<col>0</col>
			<col>1</col>
		</row>
	</layout>
</config>

=== kepingwang/cell-society/data/saved-from-society.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE config SYSTEM "cell-society.dtd">
<config>
	<name>game-of-life</name>
	<id>saved-file</id>
	<width>100.0</width>
	<height>100.0</height>
	<rows>5</rows>
	<cols>5</cols>
	<pctprimary>-1</pctprimary>
	<pctempty>-1</pctempty>
	<layout>
		<row>
			<col>1</col>
			<col>0</col>
			<col>1</col>
			<col>0</col>
			<col>1</col>
		</row>
		<row>
			<col>1</col>
			<col>1</col>
			<col>1</col>
			<col>0</col>
			<col>1</col>
		</row>
		<row>
			<col>1</col>
			<col>0</col>
			<col>0</col>
			<col>0</col>
			<col>1</col>
		</row>
		<row>
			<col>1</col>
			<col>1</col>
			<col>1</col>
			<col>0</col>
			<col>1</col>
		</row>
		<row>
			<col>1</col>
			<col>0</col>
			<col>0</col>
			<col>0</col>
			<col>1</col>
		</row>
	</layout>
</config>

=== kepingwang/cell-society/data/wator2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE config SYSTEM "cell-society.dtd">
<config>
	<name>wator</name>
	<id>keping001</id>
	<width>300</width>
	<height>300</height>
	<rows>50</rows>
	<cols>50</cols>
	<probs>
		<val>0.5</val>
		<val>0.3</val>
		<val>0.2</val>
	</probs>
	<params>
		<val>5</val>
		<val>6</val>
		<val>-10</val>
		<val>2</val>
	</params>
</config>
